
/* Drop Tables */

DROP TABLE IF EXISTS HORA.DISPLAY_DEF_M;
DROP TABLE IF EXISTS HORA.SYSTEM_PROPERTY_M;
DROP TABLE IF EXISTS HORA.M_CODE;
DROP TABLE IF EXISTS HORA.T_RESERVATION_DETAIL;
DROP TABLE IF EXISTS HORA.M_COURSE;
DROP TABLE IF EXISTS HORA.M_COURSE_GROUP;
DROP TABLE IF EXISTS HORA.T_SHIFT;
DROP TABLE IF EXISTS HORA.M_WORKING_DAY;
DROP TABLE IF EXISTS HORA.M_WORKING_DAY_DETAIL_DEFF;
DROP TABLE IF EXISTS HORA.M_WORKING_DAY_DEFF;
DROP TABLE IF EXISTS HORA.T_RESERVATION;
DROP TABLE IF EXISTS HORA.M_WORKING_STAFF;
DROP TABLE IF EXISTS HORA.M_SHOP;
DROP TABLE IF EXISTS HORA.M_STAFF;
DROP TABLE IF EXISTS HORA.M_COMPANY;
DROP TABLE IF EXISTS HORA.M_HOLIDAY;
DROP TABLE IF EXISTS HORA.M_USER;



/* Drop Sequences */

DROP SEQUENCE IF EXISTS HORA.M_CODE_CODE_ID_SEQ;
DROP SEQUENCE IF EXISTS HORA.M_COMPANY_COMPANY_ID_SEQ;
DROP SEQUENCE IF EXISTS HORA.M_COURSE_GROUP_COURSE_GROUP_ID_SEQ;
DROP SEQUENCE IF EXISTS HORA.M_HOLIDAY_HOLIDAY_ID_SEQ;
DROP SEQUENCE IF EXISTS HORA.M_SHOP_SHOP_ID_SEQ;
DROP SEQUENCE IF EXISTS HORA.M_STAFF_STAFF_ID_SEQ;
DROP SEQUENCE IF EXISTS HORA.M_USER_USER_ID_SEQ;
DROP SEQUENCE IF EXISTS HORA.M_WORKING_DAY_DEFF_M_WORKING_DAY_DEFF_ID_SEQ;
DROP SEQUENCE IF EXISTS HORA.M_WORKING_DAY_DETAIL_DEFF_WORKING_DAY_DETAIL_DEFF_ID_SEQ;
DROP SEQUENCE IF EXISTS HORA.M_WORKING_DAY_WORKING_DAY_ID_SEQ;
DROP SEQUENCE IF EXISTS HORA.M_WORKING_STAFF_WORKING_STAFF_ID_SEQ;
DROP SEQUENCE IF EXISTS HORA.T_RESERVATION_DETAIL_RESERVATION_DETAIL_ID_SEQ;
DROP SEQUENCE IF EXISTS HORA.T_RESERVATION_RESERVATION_ID_SEQ;
DROP SEQUENCE IF EXISTS HORA.T_SHIFT_SHIFT_ID_SEQ;




/* Create Tables */

-- 画面名定義_M
CREATE TABLE HORA.DISPLAY_DEF_M
(
	-- 画面ID : 画面ID
	DISPLAY_ID TEXT NOT NULL,
	-- 画面名 : 画面名
	DISPLAY_NAME TEXT,
	-- 削除フラグ
	DELETE_FLAG BOOLEAN DEFAULT 'false' NOT NULL,
	-- version_no
	VERSION_NO INT DEFAULT 1 NOT NULL,
	-- 登録日時
	REGISTER_DATETIME TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	-- 更新日時
	UPDATE_DATETIME TIMESTAMP(3),
	CONSTRAINT display_def_m_pkey PRIMARY KEY (DISPLAY_ID)
) WITHOUT OIDS;


-- システムプロパティ_M
CREATE TABLE HORA.SYSTEM_PROPERTY_M
(
	-- プロパティキー : プロパティキー
	PROP_KEY TEXT NOT NULL,
	-- プロパティグループ
	PROP_GROUP TEXT,
	-- 値 : 値
	PROP_VALUE TEXT,
	-- 説明 : 説明
	DESCRIPTION TEXT,
	-- 削除フラグ
	DELETE_FLAG BOOLEAN DEFAULT 'false' NOT NULL,
	-- version_no
	VERSION_NO INT DEFAULT 1 NOT NULL,
	-- 登録日時
	REGISTER_DATETIME TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	-- 更新日時
	UPDATE_DATETIME TIMESTAMP(3),
	CONSTRAINT system_property_m_pkey PRIMARY KEY (PROP_KEY)
) WITHOUT OIDS;


-- コードマスタ
CREATE TABLE HORA.M_CODE
(
	-- コードID : コードID
	CODE_ID SERIAL NOT NULL,
	-- グループコード : グループコード
	GROUP_CODE INT,
	-- コード1 : コード1
	CODE1 INT,
	-- コード2 : コード2
	CODE2 INT,
	-- 名称 : 名称
	NAME TEXT,
	-- 削除フラグ
	DELETE_FLAG BOOLEAN DEFAULT 'false' NOT NULL,
	-- version_no
	VERSION_NO INT DEFAULT 1 NOT NULL,
	-- 登録日時
	REGISTER_DATETIME TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	-- 更新日時
	UPDATE_DATETIME TIMESTAMP(3),
	CONSTRAINT idx_m_code_pk PRIMARY KEY (CODE_ID)
) WITHOUT OIDS;


-- 企業マスタ
CREATE TABLE HORA.M_COMPANY
(
	-- 企業ID : 企業ID
	COMPANY_ID SERIAL NOT NULL,
	-- 企業名 : 企業名
	COMPANY_NAME TEXT,
	-- 削除フラグ
	DELETE_FLAG BOOLEAN DEFAULT 'false' NOT NULL,
	-- version_no
	VERSION_NO INT DEFAULT 1 NOT NULL,
	-- 登録日時
	REGISTER_DATETIME TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	-- 更新日時
	UPDATE_DATETIME TIMESTAMP(3),
	CONSTRAINT idx_m_company_pk PRIMARY KEY (COMPANY_ID)
) WITHOUT OIDS;


-- コースマスタ
CREATE TABLE HORA.M_COURSE
(
	-- コースID : コースID
	COURSE_ID INT NOT NULL,
	-- コースグループID : コースグループID
	COURSE_GROUP_ID INT,
	-- コース名 : コース名
	COURSE_NAME TEXT,
	-- 料金 : 料金
	CHARGE INT,
	-- 所要時間 : 所要時間
	REQUIRED_TIME INTERVAL,
	-- 削除フラグ
	DELETE_FLAG BOOLEAN DEFAULT 'false' NOT NULL,
	-- version_no
	VERSION_NO INT DEFAULT 1 NOT NULL,
	-- 登録日時
	REGISTER_DATETIME TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	-- 更新日時
	UPDATE_DATETIME TIMESTAMP(3),
	CONSTRAINT idx_m_course_pk PRIMARY KEY (COURSE_ID)
) WITHOUT OIDS;


-- コースグループマスタ
CREATE TABLE HORA.M_COURSE_GROUP
(
	-- 店舗ID : 店舗ID
	SHOP_ID INT,
	-- グループ名 : グループ名
	GROUP_NAME TEXT,
	-- コースグループID : コースグループID
	COURSE_GROUP_ID SERIAL NOT NULL,
	-- 必須フラグ : 必須フラグ
	REQUIRED_FLG SMALLINT,
	-- 備考 : 備考
	REAMARKS TEXT,
	-- 削除フラグ
	DELETE_FLAG BOOLEAN DEFAULT 'false' NOT NULL,
	-- version_no
	VERSION_NO INT DEFAULT 1 NOT NULL,
	-- 登録日時
	REGISTER_DATETIME TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	-- 更新日時
	UPDATE_DATETIME TIMESTAMP(3),
	CONSTRAINT idx_m_course_group_pk PRIMARY KEY (COURSE_GROUP_ID)
) WITHOUT OIDS;


-- 祝日マスタ
CREATE TABLE HORA.M_HOLIDAY
(
	-- 祝日ID
	HOLIDAY_ID SERIAL NOT NULL,
	-- 祝日名
	HOLIDAY_NAME TEXT,
	-- 祝日
	HOLIDAY DATE NOT NULL,
	-- 削除フラグ
	DELETE_FLAG BOOLEAN DEFAULT 'false' NOT NULL,
	-- version_no
	VERSION_NO INT DEFAULT 1 NOT NULL,
	-- 登録日時
	REGISTER_DATETIME TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	-- 更新日時
	UPDATE_DATETIME TIMESTAMP(3),
	CONSTRAINT m_holiday_pkey PRIMARY KEY (HOLIDAY_ID)
) WITHOUT OIDS;


-- 店舗マスタ
CREATE TABLE HORA.M_SHOP
(
	-- 店舗ID : 店舗ID
	SHOP_ID SERIAL NOT NULL,
	-- 企業ID : 企業ID
	COMPANY_ID INT,
	-- 店舗略名 : 店舗略名
	SHOP_ABBREVIATED_NAME TEXT,
	-- 店舗名 : 店舗名
	SHOP_NAME TEXT,
	-- 電話番号1_1 : 電話番号1_1
	PHONE1_1 TEXT,
	-- 電話番号1_2 : 電話番号1_2
	PHONE1_2 TEXT,
	-- 電話番号1_3 : 電話番号1_3
	PHONE1_3 TEXT,
	-- 電話番号2_1 : 電話番号2_1
	PHONE2_1 TEXT,
	-- 電話番号2_2 : 電話番号2_2
	PHONE2_2 TEXT,
	-- 電話番号2_3 : 電話番号2_3
	PHONE2_3 TEXT,
	-- FAX_1 : FAX_1
	FAX_1 TEXT,
	-- FAX_2 : FAX_2
	FAX_2 TEXT,
	-- FAX_3 : FAX_3
	FAX_3 TEXT,
	-- メールアドレス1 : メールアドレス1
	EMAIL1 TEXT,
	-- メールアドレス2 : メールアドレス2
	EMAIL2 TEXT,
	-- URL : URL
	URL TEXT,
	-- 都道府県 : 都道府県
	PREFECTURE SMALLINT,
	-- 市区町村 : 市区町村
	CITY TEXT,
	-- その他住所1 : その他住所1
	ADDRESS1 TEXT,
	-- その他住所2 : その他住所2
	ADDRESS2 TEXT,
	-- 備考 : 備考
	REMARKS TEXT,
	-- 削除フラグ
	DELETE_FLAG BOOLEAN DEFAULT 'false' NOT NULL,
	-- version_no
	VERSION_NO INT DEFAULT 1 NOT NULL,
	-- 登録日時
	REGISTER_DATETIME TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	-- 更新日時
	UPDATE_DATETIME TIMESTAMP(3),
	CONSTRAINT idx_m_shop_pk PRIMARY KEY (SHOP_ID)
) WITHOUT OIDS;


-- スタッフマスタ
CREATE TABLE HORA.M_STAFF
(
	-- スタッフID : スタッフID
	STAFF_ID SERIAL NOT NULL,
	-- 会社id : 企業ID
	COMPANY_ID INT NOT NULL,
	-- 姓 : 姓
	FAMILY_NAME TEXT,
	-- 名 : 名
	GIVEN_NAME TEXT,
	-- 電話番号1_1 : 電話番号1_1
	PHONE1_1 TEXT,
	-- 電話番号1_2 : 電話番号1_2
	PHONE1_2 TEXT,
	-- 電話番号1_3 : 電話番号1_3
	PHONE1_3 TEXT,
	-- 削除フラグ
	DELETE_FLAG BOOLEAN DEFAULT 'false' NOT NULL,
	-- version_no
	VERSION_NO INT DEFAULT 1 NOT NULL,
	-- 登録日時
	REGISTER_DATETIME TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	-- 更新日時
	UPDATE_DATETIME TIMESTAMP(3),
	CONSTRAINT idx_m_staff_pk PRIMARY KEY (STAFF_ID)
) WITHOUT OIDS;


-- ユーザマスタ
CREATE TABLE HORA.M_USER
(
	-- ユーザID : ユーザID
	USER_ID SERIAL NOT NULL,
	-- LINE_ID
	LINE_ID TEXT,
	-- LINE_表示名
	LINE_NAME TEXT,
	-- 姓 : 姓
	FAMILY_NAME TEXT,
	-- 名 : 名
	GIVEN_NAME TEXT,
	-- 姓（カナ） : 姓（カナ）
	FAMILY_NAME_KANA TEXT,
	-- 名（カナ） : 名（カナ）
	GIVEN_NAME_KANA TEXT,
	-- 性別 : 性別
	SEX INT,
	-- 生年月日 : 生年月日
	BIRTHDAY DATE,
	-- 電話番号1_1 : 電話番号1_1
	PHONE_FIRST1 TEXT,
	-- 電話番号1_2 : 電話番号1_2
	PHONE_FIRST2 TEXT,
	-- 電話番号1_3 : 電話番号1_3
	PHONE_FIRST3 TEXT,
	-- 電話番号2_1 : 電話番号2_1
	PHONE_SECOND1 TEXT,
	-- 電話番号2_2 : 電話番号2_2
	PHONE_SECOND2 TEXT,
	-- 電話番号2_3 : 電話番号2_3
	PHONE_SECOND3 TEXT,
	-- メールアドレス1 : メールアドレス1
	EMAIL1 TEXT,
	-- メールアドレス2 : メールアドレス2
	EMAIL2 TEXT,
	-- 郵便番号 : 郵便番号
	POSTAL_CODE CHAR(7),
	-- 都道府県 : 都道府県
	PREFECTURE SMALLINT,
	-- 市区町村 : 市区町村
	CITY TEXT,
	-- その他住所1 : その他住所1
	ADDRESS1 TEXT,
	-- その他住所2 : その他住所2
	ADDRESS2 TEXT,
	-- 備考 : 備考
	REMARKS TEXT,
	-- 削除フラグ
	DELETE_FLAG BOOLEAN DEFAULT 'false' NOT NULL,
	-- version_no
	VERSION_NO INT DEFAULT 1 NOT NULL,
	-- 登録日時
	REGISTER_DATETIME TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	-- 更新日時
	UPDATE_DATETIME TIMESTAMP(3),
	CONSTRAINT idx_m_user_pk PRIMARY KEY (USER_ID)
) WITHOUT OIDS;


-- 営業日マスタ
CREATE TABLE HORA.M_WORKING_DAY
(
	-- 営業日ID : 営業日ID
	WORKING_DAY_ID SERIAL NOT NULL,
	-- 店舗ID : 店舗ID
	SHOP_ID INT,
	-- 営業日 : 営業日
	WORKING_DATE DATE,
	-- 営業開始時間 : 営業開始時間
	START_TIME TIME,
	-- 営業終了時間 : 営業終了時間
	END_TIME TIME,
	-- 削除フラグ
	DELETE_FLAG BOOLEAN DEFAULT 'false' NOT NULL,
	-- version_no
	VERSION_NO INT DEFAULT 1 NOT NULL,
	-- 登録日時
	REGISTER_DATETIME TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	-- 更新日時
	UPDATE_DATETIME TIMESTAMP(3),
	CONSTRAINT idx_m_working_day_pk PRIMARY KEY (WORKING_DAY_ID)
) WITHOUT OIDS;


-- 営業日定義マスタ
CREATE TABLE HORA.M_WORKING_DAY_DEFF
(
	-- 営業日定義ID : 営業日定義ID
	M_WORKING_DAY_DEFF_ID SERIAL NOT NULL,
	-- 店舗ID : 店舗ID
	SHOP_ID INT NOT NULL,
	-- start_day
	START_DAY DATE NOT NULL,
	-- 削除フラグ
	DELETE_FLAG BOOLEAN DEFAULT 'false' NOT NULL,
	-- version_no
	VERSION_NO INT DEFAULT 1 NOT NULL,
	-- 登録日時
	REGISTER_DATETIME TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	-- 更新日時
	UPDATE_DATETIME TIMESTAMP(3),
	CONSTRAINT idx_m_working_day_deff_pk PRIMARY KEY (M_WORKING_DAY_DEFF_ID)
) WITHOUT OIDS;


-- 営業日詳細定義マスタ
CREATE TABLE HORA.M_WORKING_DAY_DETAIL_DEFF
(
	-- 営業日詳細定義ID : 営業日詳細定義ID
	WORKING_DAY_DETAIL_DEFF_ID SERIAL NOT NULL,
	-- 営業日定義ID : 営業日定義ID
	M_WORKING_DAY_DEFF_ID INT NOT NULL,
	-- 適応フラグ : 適応フラグ
	EFFECTIVE_FLAG BOOLEAN NOT NULL,
	-- 営業日Flag : 営業日Flag
	WORKING_DAY_FLG BOOLEAN NOT NULL,
	-- 第1週Flag : 第1週Flag
	WEEK_1_FLAG BOOLEAN,
	-- 第2週Flag : 第2週Flag
	WEEK_2_FLAG BOOLEAN,
	-- 第3週Flag : 第3週Flag
	WEEK_3_FLAG BOOLEAN,
	-- 第4週Flag : 第4週Flag
	WEEK4_FLAG BOOLEAN,
	-- 第5週Flag : 第5週Flag
	WEEK5_FLAG BOOLEAN,
	-- 月曜日Flag : 月曜日Flag
	MON_FLG BOOLEAN,
	-- 火曜日Flag : 火曜日Flag
	TUE_FLG BOOLEAN,
	-- 水曜日Flag : 水曜日Flag
	WEB_FLG BOOLEAN,
	-- 木曜日Flag : 木曜日Flag
	THU_FLG BOOLEAN,
	-- 金曜日Flag : 金曜日Flag
	FRI_FLG BOOLEAN,
	-- 土曜日Flag : 土曜日Flag
	SAT_FLG BOOLEAN,
	-- 日曜日Flag : 日曜日Flag
	SUN_FLG BOOLEAN,
	-- 祝日Flag : 祝日Flag
	HOLIDAY_FLG BOOLEAN,
	-- 毎月指定日 : 毎月指定日
	DAY_OF_MONTH SMALLINT,
	-- 指定日 : 指定日
	SPECIFIED_DAY DATE,
	-- 営業開始時間 : 営業開始時間
	START_TIME TIME,
	-- 営業終了時間 : 営業終了時間
	END_TIME TIME,
	-- 削除フラグ
	DELETE_FLAG BOOLEAN DEFAULT 'false' NOT NULL,
	-- version_no
	VERSION_NO INT DEFAULT 1 NOT NULL,
	-- 登録日時
	REGISTER_DATETIME TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	-- 更新日時
	UPDATE_DATETIME TIMESTAMP(3),
	CONSTRAINT idx_m_working_day_detail_deff_pk PRIMARY KEY (WORKING_DAY_DETAIL_DEFF_ID)
) WITHOUT OIDS;


-- 所属スタッフマスタ
CREATE TABLE HORA.M_WORKING_STAFF
(
	-- 所属スタッフID : 所属スタッフID
	WORKING_STAFF_ID SERIAL NOT NULL,
	-- 店舗ID : 店舗ID
	SHOP_ID INT,
	-- スタッフID : スタッフID
	STAFF_ID INT,
	-- 削除フラグ
	DELETE_FLAG BOOLEAN DEFAULT 'false' NOT NULL,
	-- version_no
	VERSION_NO INT DEFAULT 1 NOT NULL,
	-- 登録日時
	REGISTER_DATETIME TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	-- 更新日時
	UPDATE_DATETIME TIMESTAMP(3),
	CONSTRAINT idx_m_working_staff_pk PRIMARY KEY (WORKING_STAFF_ID)
) WITHOUT OIDS;


-- 予約テーブル
CREATE TABLE HORA.T_RESERVATION
(
	-- 予約ID : 予約ID
	RESERVATION_ID BIGSERIAL NOT NULL,
	-- 店舗ID : 店舗ID
	SHOP_ID INT,
	-- 作業ing_staff_id : 所属スタッフID
	WORKING_STAFF_ID INT,
	-- ユーザID : ユーザID
	USER_ID INT,
	-- 履歴用スタッフ姓 : 履歴用スタッフ姓
	HIST_STAFF_FAMILY_NAME TEXT,
	-- 履歴用店舗名 : 履歴用店舗名
	HIST_SHOP_NAME TEXT,
	-- 履歴用店舗略名 : 履歴用店舗略名
	HIST_SHOP_ABBREVIATED_NAME TEXT,
	-- 履歴用スタッフ名 : 履歴用スタッフ名
	HIST_STAFF_GIVEN_NAME TEXT,
	-- 予約日付 : 予約日付
	RESERVATION_DATE DATE,
	-- 予約時間 : 予約時間
	RESERVATION_TIME TIME,
	-- 合計料金 : 合計料金
	TOTAL_AMOUNT INT,
	-- 備考 : 備考
	REMARKS TEXT,
	-- 状態 : 状態
	STATUS INT,
	-- 削除フラグ
	DELETE_FLAG BOOLEAN DEFAULT 'false' NOT NULL,
	-- version_no
	VERSION_NO INT DEFAULT 1 NOT NULL,
	-- 登録日時
	REGISTER_DATETIME TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	-- 更新日時
	UPDATE_DATETIME TIMESTAMP(3),
	CONSTRAINT idx_t_reservation_pk PRIMARY KEY (RESERVATION_ID)
) WITHOUT OIDS;


-- 予約明細テーブル
CREATE TABLE HORA.T_RESERVATION_DETAIL
(
	-- 予約明細ID : 予約明細ID
	RESERVATION_DETAIL_ID BIGSERIAL NOT NULL,
	-- 予約ID : 予約ID
	RESERVATION_ID BIGINT,
	-- コースID : コースID
	COURSE_ID INT,
	-- 履歴用コース名 : 履歴用コース名
	HIST_COURSE_NAME TEXT,
	-- 削除フラグ
	DELETE_FLAG BOOLEAN DEFAULT 'false' NOT NULL,
	-- version_no
	VERSION_NO INT DEFAULT 1 NOT NULL,
	-- 登録日時
	REGISTER_DATETIME TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	-- 更新日時
	UPDATE_DATETIME TIMESTAMP(3),
	CONSTRAINT idx_t_reservation_detail_pk PRIMARY KEY (RESERVATION_DETAIL_ID)
) WITHOUT OIDS;


-- シフトテーブル
CREATE TABLE HORA.T_SHIFT
(
	-- シフトID : シフトID
	SHIFT_ID SERIAL NOT NULL,
	-- 作業ing_staff_id : 所属スタッフID
	WORKING_STAFF_ID INT NOT NULL,
	-- 営業日ID : 営業日ID
	WORKING_DAY_ID INT,
	-- 開始時間 : 開始時間
	START_TIME TIME,
	-- 終了時間 : 終了時間
	END_TIME TIME,
	-- 削除フラグ
	DELETE_FLAG BOOLEAN DEFAULT 'false' NOT NULL,
	-- version_no
	VERSION_NO INT DEFAULT 1 NOT NULL,
	-- 登録日時
	REGISTER_DATETIME TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	-- 更新日時
	UPDATE_DATETIME TIMESTAMP(3),
	CONSTRAINT idx_t_shift_pk PRIMARY KEY (SHIFT_ID)
) WITHOUT OIDS;



/* Create Foreign Keys */

ALTER TABLE HORA.M_SHOP
	ADD CONSTRAINT IDX_M_SHOP_FK0 FOREIGN KEY (COMPANY_ID)
	REFERENCES HORA.M_COMPANY (COMPANY_ID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE HORA.M_STAFF
	ADD CONSTRAINT M_STAFF_COMPANY_ID_FKEY FOREIGN KEY (COMPANY_ID)
	REFERENCES HORA.M_COMPANY (COMPANY_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE HORA.T_RESERVATION_DETAIL
	ADD CONSTRAINT IDX_T_RESERVATION_DETAIL_FK2 FOREIGN KEY (COURSE_ID)
	REFERENCES HORA.M_COURSE (COURSE_ID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE HORA.M_COURSE
	ADD CONSTRAINT IDX_M_COURSE_FK0 FOREIGN KEY (COURSE_GROUP_ID)
	REFERENCES HORA.M_COURSE_GROUP (COURSE_GROUP_ID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE HORA.M_COURSE_GROUP
	ADD CONSTRAINT IDX_M_COURSE_GROUP_FK0 FOREIGN KEY (SHOP_ID)
	REFERENCES HORA.M_SHOP (SHOP_ID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE HORA.M_WORKING_DAY
	ADD CONSTRAINT IDX_M_WORKING_DAY_FK0 FOREIGN KEY (SHOP_ID)
	REFERENCES HORA.M_SHOP (SHOP_ID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE HORA.M_WORKING_DAY_DEFF
	ADD CONSTRAINT IDX_M_WORKING_DAY_DEFF_FK0 FOREIGN KEY (SHOP_ID)
	REFERENCES HORA.M_SHOP (SHOP_ID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE HORA.M_WORKING_STAFF
	ADD CONSTRAINT IDX_M_WORKING_STAFF_FK0 FOREIGN KEY (SHOP_ID)
	REFERENCES HORA.M_SHOP (SHOP_ID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE HORA.T_RESERVATION
	ADD CONSTRAINT IDX_T_RESERVATION_FK1 FOREIGN KEY (SHOP_ID)
	REFERENCES HORA.M_SHOP (SHOP_ID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE HORA.M_WORKING_STAFF
	ADD CONSTRAINT IDX_M_WORKING_STAFF_FK1 FOREIGN KEY (STAFF_ID)
	REFERENCES HORA.M_STAFF (STAFF_ID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE HORA.T_RESERVATION
	ADD CONSTRAINT IDX_T_RESERVATION_FK0 FOREIGN KEY (USER_ID)
	REFERENCES HORA.M_USER (USER_ID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE HORA.T_SHIFT
	ADD CONSTRAINT IDX_T_SHIFT_FK0 FOREIGN KEY (WORKING_DAY_ID)
	REFERENCES HORA.M_WORKING_DAY (WORKING_DAY_ID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE HORA.M_WORKING_DAY_DETAIL_DEFF
	ADD CONSTRAINT IDX_M_WORKING_DAY_DETAIL_DEFF_FK1 FOREIGN KEY (M_WORKING_DAY_DEFF_ID)
	REFERENCES HORA.M_WORKING_DAY_DEFF (M_WORKING_DAY_DEFF_ID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE HORA.T_RESERVATION
	ADD CONSTRAINT T_RESERVATION_WORKING_STAFF_ID_FKEY FOREIGN KEY (WORKING_STAFF_ID)
	REFERENCES HORA.M_WORKING_STAFF (WORKING_STAFF_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE HORA.T_SHIFT
	ADD CONSTRAINT T_SHIFT_WORKING_STAFF_ID_FKEY FOREIGN KEY (WORKING_STAFF_ID)
	REFERENCES HORA.M_WORKING_STAFF (WORKING_STAFF_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE HORA.T_RESERVATION_DETAIL
	ADD CONSTRAINT IDX_T_RESERVATION_DETAIL_FK0 FOREIGN KEY (RESERVATION_ID)
	REFERENCES HORA.T_RESERVATION (RESERVATION_ID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;



/* Comments */

COMMENT ON TABLE HORA.DISPLAY_DEF_M IS '画面名定義_M';
COMMENT ON COLUMN HORA.DISPLAY_DEF_M.DISPLAY_ID IS '画面ID : 画面ID';
COMMENT ON COLUMN HORA.DISPLAY_DEF_M.DISPLAY_NAME IS '画面名 : 画面名';
COMMENT ON COLUMN HORA.DISPLAY_DEF_M.DELETE_FLAG IS '削除フラグ';
COMMENT ON COLUMN HORA.DISPLAY_DEF_M.VERSION_NO IS 'version_no';
COMMENT ON COLUMN HORA.DISPLAY_DEF_M.REGISTER_DATETIME IS '登録日時';
COMMENT ON COLUMN HORA.DISPLAY_DEF_M.UPDATE_DATETIME IS '更新日時';
COMMENT ON TABLE HORA.SYSTEM_PROPERTY_M IS 'システムプロパティ_M';
COMMENT ON COLUMN HORA.SYSTEM_PROPERTY_M.PROP_KEY IS 'プロパティキー : プロパティキー';
COMMENT ON COLUMN HORA.SYSTEM_PROPERTY_M.PROP_GROUP IS 'プロパティグループ';
COMMENT ON COLUMN HORA.SYSTEM_PROPERTY_M.PROP_VALUE IS '値 : 値';
COMMENT ON COLUMN HORA.SYSTEM_PROPERTY_M.DESCRIPTION IS '説明 : 説明';
COMMENT ON COLUMN HORA.SYSTEM_PROPERTY_M.DELETE_FLAG IS '削除フラグ';
COMMENT ON COLUMN HORA.SYSTEM_PROPERTY_M.VERSION_NO IS 'version_no';
COMMENT ON COLUMN HORA.SYSTEM_PROPERTY_M.REGISTER_DATETIME IS '登録日時';
COMMENT ON COLUMN HORA.SYSTEM_PROPERTY_M.UPDATE_DATETIME IS '更新日時';
COMMENT ON TABLE HORA.M_CODE IS 'コードマスタ';
COMMENT ON COLUMN HORA.M_CODE.CODE_ID IS 'コードID : コードID';
COMMENT ON COLUMN HORA.M_CODE.GROUP_CODE IS 'グループコード : グループコード';
COMMENT ON COLUMN HORA.M_CODE.CODE1 IS 'コード1 : コード1';
COMMENT ON COLUMN HORA.M_CODE.CODE2 IS 'コード2 : コード2';
COMMENT ON COLUMN HORA.M_CODE.NAME IS '名称 : 名称';
COMMENT ON COLUMN HORA.M_CODE.DELETE_FLAG IS '削除フラグ';
COMMENT ON COLUMN HORA.M_CODE.VERSION_NO IS 'version_no';
COMMENT ON COLUMN HORA.M_CODE.REGISTER_DATETIME IS '登録日時';
COMMENT ON COLUMN HORA.M_CODE.UPDATE_DATETIME IS '更新日時';
COMMENT ON TABLE HORA.M_COMPANY IS '企業マスタ';
COMMENT ON COLUMN HORA.M_COMPANY.COMPANY_ID IS '企業ID : 企業ID';
COMMENT ON COLUMN HORA.M_COMPANY.COMPANY_NAME IS '企業名 : 企業名';
COMMENT ON COLUMN HORA.M_COMPANY.DELETE_FLAG IS '削除フラグ';
COMMENT ON COLUMN HORA.M_COMPANY.VERSION_NO IS 'version_no';
COMMENT ON COLUMN HORA.M_COMPANY.REGISTER_DATETIME IS '登録日時';
COMMENT ON COLUMN HORA.M_COMPANY.UPDATE_DATETIME IS '更新日時';
COMMENT ON TABLE HORA.M_COURSE IS 'コースマスタ';
COMMENT ON COLUMN HORA.M_COURSE.COURSE_ID IS 'コースID : コースID';
COMMENT ON COLUMN HORA.M_COURSE.COURSE_GROUP_ID IS 'コースグループID : コースグループID';
COMMENT ON COLUMN HORA.M_COURSE.COURSE_NAME IS 'コース名 : コース名';
COMMENT ON COLUMN HORA.M_COURSE.CHARGE IS '料金 : 料金';
COMMENT ON COLUMN HORA.M_COURSE.REQUIRED_TIME IS '所要時間 : 所要時間';
COMMENT ON COLUMN HORA.M_COURSE.DELETE_FLAG IS '削除フラグ';
COMMENT ON COLUMN HORA.M_COURSE.VERSION_NO IS 'version_no';
COMMENT ON COLUMN HORA.M_COURSE.REGISTER_DATETIME IS '登録日時';
COMMENT ON COLUMN HORA.M_COURSE.UPDATE_DATETIME IS '更新日時';
COMMENT ON TABLE HORA.M_COURSE_GROUP IS 'コースグループマスタ';
COMMENT ON COLUMN HORA.M_COURSE_GROUP.SHOP_ID IS '店舗ID : 店舗ID';
COMMENT ON COLUMN HORA.M_COURSE_GROUP.GROUP_NAME IS 'グループ名 : グループ名';
COMMENT ON COLUMN HORA.M_COURSE_GROUP.COURSE_GROUP_ID IS 'コースグループID : コースグループID';
COMMENT ON COLUMN HORA.M_COURSE_GROUP.REQUIRED_FLG IS '必須フラグ : 必須フラグ';
COMMENT ON COLUMN HORA.M_COURSE_GROUP.REAMARKS IS '備考 : 備考';
COMMENT ON COLUMN HORA.M_COURSE_GROUP.DELETE_FLAG IS '削除フラグ';
COMMENT ON COLUMN HORA.M_COURSE_GROUP.VERSION_NO IS 'version_no';
COMMENT ON COLUMN HORA.M_COURSE_GROUP.REGISTER_DATETIME IS '登録日時';
COMMENT ON COLUMN HORA.M_COURSE_GROUP.UPDATE_DATETIME IS '更新日時';
COMMENT ON TABLE HORA.M_HOLIDAY IS '祝日マスタ';
COMMENT ON COLUMN HORA.M_HOLIDAY.HOLIDAY_ID IS '祝日ID';
COMMENT ON COLUMN HORA.M_HOLIDAY.HOLIDAY_NAME IS '祝日名';
COMMENT ON COLUMN HORA.M_HOLIDAY.HOLIDAY IS '祝日';
COMMENT ON COLUMN HORA.M_HOLIDAY.DELETE_FLAG IS '削除フラグ';
COMMENT ON COLUMN HORA.M_HOLIDAY.VERSION_NO IS 'version_no';
COMMENT ON COLUMN HORA.M_HOLIDAY.REGISTER_DATETIME IS '登録日時';
COMMENT ON COLUMN HORA.M_HOLIDAY.UPDATE_DATETIME IS '更新日時';
COMMENT ON TABLE HORA.M_SHOP IS '店舗マスタ';
COMMENT ON COLUMN HORA.M_SHOP.SHOP_ID IS '店舗ID : 店舗ID';
COMMENT ON COLUMN HORA.M_SHOP.COMPANY_ID IS '企業ID : 企業ID';
COMMENT ON COLUMN HORA.M_SHOP.SHOP_ABBREVIATED_NAME IS '店舗略名 : 店舗略名';
COMMENT ON COLUMN HORA.M_SHOP.SHOP_NAME IS '店舗名 : 店舗名';
COMMENT ON COLUMN HORA.M_SHOP.PHONE1_1 IS '電話番号1_1 : 電話番号1_1';
COMMENT ON COLUMN HORA.M_SHOP.PHONE1_2 IS '電話番号1_2 : 電話番号1_2';
COMMENT ON COLUMN HORA.M_SHOP.PHONE1_3 IS '電話番号1_3 : 電話番号1_3';
COMMENT ON COLUMN HORA.M_SHOP.PHONE2_1 IS '電話番号2_1 : 電話番号2_1';
COMMENT ON COLUMN HORA.M_SHOP.PHONE2_2 IS '電話番号2_2 : 電話番号2_2';
COMMENT ON COLUMN HORA.M_SHOP.PHONE2_3 IS '電話番号2_3 : 電話番号2_3';
COMMENT ON COLUMN HORA.M_SHOP.FAX_1 IS 'FAX_1 : FAX_1';
COMMENT ON COLUMN HORA.M_SHOP.FAX_2 IS 'FAX_2 : FAX_2';
COMMENT ON COLUMN HORA.M_SHOP.FAX_3 IS 'FAX_3 : FAX_3';
COMMENT ON COLUMN HORA.M_SHOP.EMAIL1 IS 'メールアドレス1 : メールアドレス1';
COMMENT ON COLUMN HORA.M_SHOP.EMAIL2 IS 'メールアドレス2 : メールアドレス2';
COMMENT ON COLUMN HORA.M_SHOP.URL IS 'URL : URL';
COMMENT ON COLUMN HORA.M_SHOP.PREFECTURE IS '都道府県 : 都道府県';
COMMENT ON COLUMN HORA.M_SHOP.CITY IS '市区町村 : 市区町村';
COMMENT ON COLUMN HORA.M_SHOP.ADDRESS1 IS 'その他住所1 : その他住所1';
COMMENT ON COLUMN HORA.M_SHOP.ADDRESS2 IS 'その他住所2 : その他住所2';
COMMENT ON COLUMN HORA.M_SHOP.REMARKS IS '備考 : 備考';
COMMENT ON COLUMN HORA.M_SHOP.DELETE_FLAG IS '削除フラグ';
COMMENT ON COLUMN HORA.M_SHOP.VERSION_NO IS 'version_no';
COMMENT ON COLUMN HORA.M_SHOP.REGISTER_DATETIME IS '登録日時';
COMMENT ON COLUMN HORA.M_SHOP.UPDATE_DATETIME IS '更新日時';
COMMENT ON TABLE HORA.M_STAFF IS 'スタッフマスタ';
COMMENT ON COLUMN HORA.M_STAFF.STAFF_ID IS 'スタッフID : スタッフID';
COMMENT ON COLUMN HORA.M_STAFF.COMPANY_ID IS '会社id : 企業ID';
COMMENT ON COLUMN HORA.M_STAFF.FAMILY_NAME IS '姓 : 姓';
COMMENT ON COLUMN HORA.M_STAFF.GIVEN_NAME IS '名 : 名';
COMMENT ON COLUMN HORA.M_STAFF.PHONE1_1 IS '電話番号1_1 : 電話番号1_1';
COMMENT ON COLUMN HORA.M_STAFF.PHONE1_2 IS '電話番号1_2 : 電話番号1_2';
COMMENT ON COLUMN HORA.M_STAFF.PHONE1_3 IS '電話番号1_3 : 電話番号1_3';
COMMENT ON COLUMN HORA.M_STAFF.DELETE_FLAG IS '削除フラグ';
COMMENT ON COLUMN HORA.M_STAFF.VERSION_NO IS 'version_no';
COMMENT ON COLUMN HORA.M_STAFF.REGISTER_DATETIME IS '登録日時';
COMMENT ON COLUMN HORA.M_STAFF.UPDATE_DATETIME IS '更新日時';
COMMENT ON TABLE HORA.M_USER IS 'ユーザマスタ';
COMMENT ON COLUMN HORA.M_USER.USER_ID IS 'ユーザID : ユーザID';
COMMENT ON COLUMN HORA.M_USER.LINE_ID IS 'LINE_ID';
COMMENT ON COLUMN HORA.M_USER.LINE_NAME IS 'LINE_表示名';
COMMENT ON COLUMN HORA.M_USER.FAMILY_NAME IS '姓 : 姓';
COMMENT ON COLUMN HORA.M_USER.GIVEN_NAME IS '名 : 名';
COMMENT ON COLUMN HORA.M_USER.FAMILY_NAME_KANA IS '姓（カナ） : 姓（カナ）';
COMMENT ON COLUMN HORA.M_USER.GIVEN_NAME_KANA IS '名（カナ） : 名（カナ）';
COMMENT ON COLUMN HORA.M_USER.SEX IS '性別 : 性別';
COMMENT ON COLUMN HORA.M_USER.BIRTHDAY IS '生年月日 : 生年月日';
COMMENT ON COLUMN HORA.M_USER.PHONE_FIRST1 IS '電話番号1_1 : 電話番号1_1';
COMMENT ON COLUMN HORA.M_USER.PHONE_FIRST2 IS '電話番号1_2 : 電話番号1_2';
COMMENT ON COLUMN HORA.M_USER.PHONE_FIRST3 IS '電話番号1_3 : 電話番号1_3';
COMMENT ON COLUMN HORA.M_USER.PHONE_SECOND1 IS '電話番号2_1 : 電話番号2_1';
COMMENT ON COLUMN HORA.M_USER.PHONE_SECOND2 IS '電話番号2_2 : 電話番号2_2';
COMMENT ON COLUMN HORA.M_USER.PHONE_SECOND3 IS '電話番号2_3 : 電話番号2_3';
COMMENT ON COLUMN HORA.M_USER.EMAIL1 IS 'メールアドレス1 : メールアドレス1';
COMMENT ON COLUMN HORA.M_USER.EMAIL2 IS 'メールアドレス2 : メールアドレス2';
COMMENT ON COLUMN HORA.M_USER.POSTAL_CODE IS '郵便番号 : 郵便番号';
COMMENT ON COLUMN HORA.M_USER.PREFECTURE IS '都道府県 : 都道府県';
COMMENT ON COLUMN HORA.M_USER.CITY IS '市区町村 : 市区町村';
COMMENT ON COLUMN HORA.M_USER.ADDRESS1 IS 'その他住所1 : その他住所1';
COMMENT ON COLUMN HORA.M_USER.ADDRESS2 IS 'その他住所2 : その他住所2';
COMMENT ON COLUMN HORA.M_USER.REMARKS IS '備考 : 備考';
COMMENT ON COLUMN HORA.M_USER.DELETE_FLAG IS '削除フラグ';
COMMENT ON COLUMN HORA.M_USER.VERSION_NO IS 'version_no';
COMMENT ON COLUMN HORA.M_USER.REGISTER_DATETIME IS '登録日時';
COMMENT ON COLUMN HORA.M_USER.UPDATE_DATETIME IS '更新日時';
COMMENT ON TABLE HORA.M_WORKING_DAY IS '営業日マスタ';
COMMENT ON COLUMN HORA.M_WORKING_DAY.WORKING_DAY_ID IS '営業日ID : 営業日ID';
COMMENT ON COLUMN HORA.M_WORKING_DAY.SHOP_ID IS '店舗ID : 店舗ID';
COMMENT ON COLUMN HORA.M_WORKING_DAY.WORKING_DATE IS '営業日 : 営業日';
COMMENT ON COLUMN HORA.M_WORKING_DAY.START_TIME IS '営業開始時間 : 営業開始時間';
COMMENT ON COLUMN HORA.M_WORKING_DAY.END_TIME IS '営業終了時間 : 営業終了時間';
COMMENT ON COLUMN HORA.M_WORKING_DAY.DELETE_FLAG IS '削除フラグ';
COMMENT ON COLUMN HORA.M_WORKING_DAY.VERSION_NO IS 'version_no';
COMMENT ON COLUMN HORA.M_WORKING_DAY.REGISTER_DATETIME IS '登録日時';
COMMENT ON COLUMN HORA.M_WORKING_DAY.UPDATE_DATETIME IS '更新日時';
COMMENT ON TABLE HORA.M_WORKING_DAY_DEFF IS '営業日定義マスタ';
COMMENT ON COLUMN HORA.M_WORKING_DAY_DEFF.M_WORKING_DAY_DEFF_ID IS '営業日定義ID : 営業日定義ID';
COMMENT ON COLUMN HORA.M_WORKING_DAY_DEFF.SHOP_ID IS '店舗ID : 店舗ID';
COMMENT ON COLUMN HORA.M_WORKING_DAY_DEFF.START_DAY IS 'start_day';
COMMENT ON COLUMN HORA.M_WORKING_DAY_DEFF.DELETE_FLAG IS '削除フラグ';
COMMENT ON COLUMN HORA.M_WORKING_DAY_DEFF.VERSION_NO IS 'version_no';
COMMENT ON COLUMN HORA.M_WORKING_DAY_DEFF.REGISTER_DATETIME IS '登録日時';
COMMENT ON COLUMN HORA.M_WORKING_DAY_DEFF.UPDATE_DATETIME IS '更新日時';
COMMENT ON TABLE HORA.M_WORKING_DAY_DETAIL_DEFF IS '営業日詳細定義マスタ';
COMMENT ON COLUMN HORA.M_WORKING_DAY_DETAIL_DEFF.WORKING_DAY_DETAIL_DEFF_ID IS '営業日詳細定義ID : 営業日詳細定義ID';
COMMENT ON COLUMN HORA.M_WORKING_DAY_DETAIL_DEFF.M_WORKING_DAY_DEFF_ID IS '営業日定義ID : 営業日定義ID';
COMMENT ON COLUMN HORA.M_WORKING_DAY_DETAIL_DEFF.EFFECTIVE_FLAG IS '適応フラグ : 適応フラグ';
COMMENT ON COLUMN HORA.M_WORKING_DAY_DETAIL_DEFF.WORKING_DAY_FLG IS '営業日Flag : 営業日Flag';
COMMENT ON COLUMN HORA.M_WORKING_DAY_DETAIL_DEFF.WEEK_1_FLAG IS '第1週Flag : 第1週Flag';
COMMENT ON COLUMN HORA.M_WORKING_DAY_DETAIL_DEFF.WEEK_2_FLAG IS '第2週Flag : 第2週Flag';
COMMENT ON COLUMN HORA.M_WORKING_DAY_DETAIL_DEFF.WEEK_3_FLAG IS '第3週Flag : 第3週Flag';
COMMENT ON COLUMN HORA.M_WORKING_DAY_DETAIL_DEFF.WEEK4_FLAG IS '第4週Flag : 第4週Flag';
COMMENT ON COLUMN HORA.M_WORKING_DAY_DETAIL_DEFF.WEEK5_FLAG IS '第5週Flag : 第5週Flag';
COMMENT ON COLUMN HORA.M_WORKING_DAY_DETAIL_DEFF.MON_FLG IS '月曜日Flag : 月曜日Flag';
COMMENT ON COLUMN HORA.M_WORKING_DAY_DETAIL_DEFF.TUE_FLG IS '火曜日Flag : 火曜日Flag';
COMMENT ON COLUMN HORA.M_WORKING_DAY_DETAIL_DEFF.WEB_FLG IS '水曜日Flag : 水曜日Flag';
COMMENT ON COLUMN HORA.M_WORKING_DAY_DETAIL_DEFF.THU_FLG IS '木曜日Flag : 木曜日Flag';
COMMENT ON COLUMN HORA.M_WORKING_DAY_DETAIL_DEFF.FRI_FLG IS '金曜日Flag : 金曜日Flag';
COMMENT ON COLUMN HORA.M_WORKING_DAY_DETAIL_DEFF.SAT_FLG IS '土曜日Flag : 土曜日Flag';
COMMENT ON COLUMN HORA.M_WORKING_DAY_DETAIL_DEFF.SUN_FLG IS '日曜日Flag : 日曜日Flag';
COMMENT ON COLUMN HORA.M_WORKING_DAY_DETAIL_DEFF.HOLIDAY_FLG IS '祝日Flag : 祝日Flag';
COMMENT ON COLUMN HORA.M_WORKING_DAY_DETAIL_DEFF.DAY_OF_MONTH IS '毎月指定日 : 毎月指定日';
COMMENT ON COLUMN HORA.M_WORKING_DAY_DETAIL_DEFF.SPECIFIED_DAY IS '指定日 : 指定日';
COMMENT ON COLUMN HORA.M_WORKING_DAY_DETAIL_DEFF.START_TIME IS '営業開始時間 : 営業開始時間';
COMMENT ON COLUMN HORA.M_WORKING_DAY_DETAIL_DEFF.END_TIME IS '営業終了時間 : 営業終了時間';
COMMENT ON COLUMN HORA.M_WORKING_DAY_DETAIL_DEFF.DELETE_FLAG IS '削除フラグ';
COMMENT ON COLUMN HORA.M_WORKING_DAY_DETAIL_DEFF.VERSION_NO IS 'version_no';
COMMENT ON COLUMN HORA.M_WORKING_DAY_DETAIL_DEFF.REGISTER_DATETIME IS '登録日時';
COMMENT ON COLUMN HORA.M_WORKING_DAY_DETAIL_DEFF.UPDATE_DATETIME IS '更新日時';
COMMENT ON TABLE HORA.M_WORKING_STAFF IS '所属スタッフマスタ';
COMMENT ON COLUMN HORA.M_WORKING_STAFF.WORKING_STAFF_ID IS '所属スタッフID : 所属スタッフID';
COMMENT ON COLUMN HORA.M_WORKING_STAFF.SHOP_ID IS '店舗ID : 店舗ID';
COMMENT ON COLUMN HORA.M_WORKING_STAFF.STAFF_ID IS 'スタッフID : スタッフID';
COMMENT ON COLUMN HORA.M_WORKING_STAFF.DELETE_FLAG IS '削除フラグ';
COMMENT ON COLUMN HORA.M_WORKING_STAFF.VERSION_NO IS 'version_no';
COMMENT ON COLUMN HORA.M_WORKING_STAFF.REGISTER_DATETIME IS '登録日時';
COMMENT ON COLUMN HORA.M_WORKING_STAFF.UPDATE_DATETIME IS '更新日時';
COMMENT ON TABLE HORA.T_RESERVATION IS '予約テーブル';
COMMENT ON COLUMN HORA.T_RESERVATION.RESERVATION_ID IS '予約ID : 予約ID';
COMMENT ON COLUMN HORA.T_RESERVATION.SHOP_ID IS '店舗ID : 店舗ID';
COMMENT ON COLUMN HORA.T_RESERVATION.WORKING_STAFF_ID IS '作業ing_staff_id : 所属スタッフID';
COMMENT ON COLUMN HORA.T_RESERVATION.USER_ID IS 'ユーザID : ユーザID';
COMMENT ON COLUMN HORA.T_RESERVATION.HIST_STAFF_FAMILY_NAME IS '履歴用スタッフ姓 : 履歴用スタッフ姓';
COMMENT ON COLUMN HORA.T_RESERVATION.HIST_SHOP_NAME IS '履歴用店舗名 : 履歴用店舗名';
COMMENT ON COLUMN HORA.T_RESERVATION.HIST_SHOP_ABBREVIATED_NAME IS '履歴用店舗略名 : 履歴用店舗略名';
COMMENT ON COLUMN HORA.T_RESERVATION.HIST_STAFF_GIVEN_NAME IS '履歴用スタッフ名 : 履歴用スタッフ名';
COMMENT ON COLUMN HORA.T_RESERVATION.RESERVATION_DATE IS '予約日付 : 予約日付';
COMMENT ON COLUMN HORA.T_RESERVATION.RESERVATION_TIME IS '予約時間 : 予約時間';
COMMENT ON COLUMN HORA.T_RESERVATION.TOTAL_AMOUNT IS '合計料金 : 合計料金';
COMMENT ON COLUMN HORA.T_RESERVATION.REMARKS IS '備考 : 備考';
COMMENT ON COLUMN HORA.T_RESERVATION.STATUS IS '状態 : 状態';
COMMENT ON COLUMN HORA.T_RESERVATION.DELETE_FLAG IS '削除フラグ';
COMMENT ON COLUMN HORA.T_RESERVATION.VERSION_NO IS 'version_no';
COMMENT ON COLUMN HORA.T_RESERVATION.REGISTER_DATETIME IS '登録日時';
COMMENT ON COLUMN HORA.T_RESERVATION.UPDATE_DATETIME IS '更新日時';
COMMENT ON TABLE HORA.T_RESERVATION_DETAIL IS '予約明細テーブル';
COMMENT ON COLUMN HORA.T_RESERVATION_DETAIL.RESERVATION_DETAIL_ID IS '予約明細ID : 予約明細ID';
COMMENT ON COLUMN HORA.T_RESERVATION_DETAIL.RESERVATION_ID IS '予約ID : 予約ID';
COMMENT ON COLUMN HORA.T_RESERVATION_DETAIL.COURSE_ID IS 'コースID : コースID';
COMMENT ON COLUMN HORA.T_RESERVATION_DETAIL.HIST_COURSE_NAME IS '履歴用コース名 : 履歴用コース名';
COMMENT ON COLUMN HORA.T_RESERVATION_DETAIL.DELETE_FLAG IS '削除フラグ';
COMMENT ON COLUMN HORA.T_RESERVATION_DETAIL.VERSION_NO IS 'version_no';
COMMENT ON COLUMN HORA.T_RESERVATION_DETAIL.REGISTER_DATETIME IS '登録日時';
COMMENT ON COLUMN HORA.T_RESERVATION_DETAIL.UPDATE_DATETIME IS '更新日時';
COMMENT ON TABLE HORA.T_SHIFT IS 'シフトテーブル';
COMMENT ON COLUMN HORA.T_SHIFT.SHIFT_ID IS 'シフトID : シフトID';
COMMENT ON COLUMN HORA.T_SHIFT.WORKING_STAFF_ID IS '作業ing_staff_id : 所属スタッフID';
COMMENT ON COLUMN HORA.T_SHIFT.WORKING_DAY_ID IS '営業日ID : 営業日ID';
COMMENT ON COLUMN HORA.T_SHIFT.START_TIME IS '開始時間 : 開始時間';
COMMENT ON COLUMN HORA.T_SHIFT.END_TIME IS '終了時間 : 終了時間';
COMMENT ON COLUMN HORA.T_SHIFT.DELETE_FLAG IS '削除フラグ';
COMMENT ON COLUMN HORA.T_SHIFT.VERSION_NO IS 'version_no';
COMMENT ON COLUMN HORA.T_SHIFT.REGISTER_DATETIME IS '登録日時';
COMMENT ON COLUMN HORA.T_SHIFT.UPDATE_DATETIME IS '更新日時';



